// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.navideck.universal_ble

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object UniversalBlePeripheralPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class PeripheralBondState(val raw: Int) {
  BONDING(0),
  BONDED(1),
  NONE(2);

  companion object {
    fun ofRaw(raw: Int): PeripheralBondState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralService (
  val uuid: String,
  val primary: Boolean,
  val characteristics: List<PeripheralCharacteristic>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralService {
      val uuid = pigeonVar_list[0] as String
      val primary = pigeonVar_list[1] as Boolean
      val characteristics = pigeonVar_list[2] as List<PeripheralCharacteristic>
      return PeripheralService(uuid, primary, characteristics)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      primary,
      characteristics,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PeripheralService
    return UniversalBlePeripheralPigeonUtils.deepEquals(this.uuid, other.uuid) && UniversalBlePeripheralPigeonUtils.deepEquals(this.primary, other.primary) && UniversalBlePeripheralPigeonUtils.deepEquals(this.characteristics, other.characteristics)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.uuid)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.primary)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.characteristics)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralCharacteristic (
  val uuid: String,
  val properties: List<Long>,
  val permissions: List<Long>,
  val descriptors: List<PeripheralDescriptor>? = null,
  val value: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralCharacteristic {
      val uuid = pigeonVar_list[0] as String
      val properties = pigeonVar_list[1] as List<Long>
      val permissions = pigeonVar_list[2] as List<Long>
      val descriptors = pigeonVar_list[3] as List<PeripheralDescriptor>?
      val value = pigeonVar_list[4] as ByteArray?
      return PeripheralCharacteristic(uuid, properties, permissions, descriptors, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      properties,
      permissions,
      descriptors,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PeripheralCharacteristic
    return UniversalBlePeripheralPigeonUtils.deepEquals(this.uuid, other.uuid) && UniversalBlePeripheralPigeonUtils.deepEquals(this.properties, other.properties) && UniversalBlePeripheralPigeonUtils.deepEquals(this.permissions, other.permissions) && UniversalBlePeripheralPigeonUtils.deepEquals(this.descriptors, other.descriptors) && UniversalBlePeripheralPigeonUtils.deepEquals(this.value, other.value)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.uuid)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.properties)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.permissions)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.descriptors)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.value)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralDescriptor (
  val uuid: String,
  val value: ByteArray? = null,
  val permissions: List<Long>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralDescriptor {
      val uuid = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as ByteArray?
      val permissions = pigeonVar_list[2] as List<Long>?
      return PeripheralDescriptor(uuid, value, permissions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      value,
      permissions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PeripheralDescriptor
    return UniversalBlePeripheralPigeonUtils.deepEquals(this.uuid, other.uuid) && UniversalBlePeripheralPigeonUtils.deepEquals(this.value, other.value) && UniversalBlePeripheralPigeonUtils.deepEquals(this.permissions, other.permissions)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.uuid)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.value)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.permissions)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralReadRequestResult (
  val value: ByteArray,
  val offset: Long? = null,
  val status: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralReadRequestResult {
      val value = pigeonVar_list[0] as ByteArray
      val offset = pigeonVar_list[1] as Long?
      val status = pigeonVar_list[2] as Long?
      return PeripheralReadRequestResult(value, offset, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      value,
      offset,
      status,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PeripheralReadRequestResult
    return UniversalBlePeripheralPigeonUtils.deepEquals(this.value, other.value) && UniversalBlePeripheralPigeonUtils.deepEquals(this.offset, other.offset) && UniversalBlePeripheralPigeonUtils.deepEquals(this.status, other.status)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.value)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.offset)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.status)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralWriteRequestResult (
  val value: ByteArray? = null,
  val offset: Long? = null,
  val status: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralWriteRequestResult {
      val value = pigeonVar_list[0] as ByteArray?
      val offset = pigeonVar_list[1] as Long?
      val status = pigeonVar_list[2] as Long?
      return PeripheralWriteRequestResult(value, offset, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      value,
      offset,
      status,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PeripheralWriteRequestResult
    return UniversalBlePeripheralPigeonUtils.deepEquals(this.value, other.value) && UniversalBlePeripheralPigeonUtils.deepEquals(this.offset, other.offset) && UniversalBlePeripheralPigeonUtils.deepEquals(this.status, other.status)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.value)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.offset)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.status)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralManufacturerData (
  val manufacturerId: Long,
  val data: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralManufacturerData {
      val manufacturerId = pigeonVar_list[0] as Long
      val data = pigeonVar_list[1] as ByteArray
      return PeripheralManufacturerData(manufacturerId, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      manufacturerId,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PeripheralManufacturerData
    return UniversalBlePeripheralPigeonUtils.deepEquals(this.manufacturerId, other.manufacturerId) && UniversalBlePeripheralPigeonUtils.deepEquals(this.data, other.data)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.manufacturerId)
    result = 31 * result + UniversalBlePeripheralPigeonUtils.deepHash(this.data)
    return result
  }
}
private open class UniversalBlePeripheralPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PeripheralBondState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralService.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralCharacteristic.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralDescriptor.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralReadRequestResult.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralWriteRequestResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralManufacturerData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PeripheralBondState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PeripheralService -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PeripheralCharacteristic -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PeripheralDescriptor -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PeripheralReadRequestResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PeripheralWriteRequestResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PeripheralManufacturerData -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface UniversalBlePeripheralChannel {
  fun initialize()
  fun isAdvertising(): Boolean?
  fun isSupported(): Boolean
  fun stopAdvertising()
  fun addService(service: PeripheralService)
  fun removeService(serviceId: String)
  fun clearServices()
  fun getServices(): List<String>
  fun startAdvertising(services: List<String>, localName: String?, timeout: Long?, manufacturerData: PeripheralManufacturerData?, addManufacturerDataInScanResponse: Boolean)
  fun updateCharacteristic(characteristicId: String, value: ByteArray, deviceId: String?)
  /**
   * Returns peripheral-central device ids currently subscribed to [characteristicId]
   * (e.g. HID report characteristic). Used to restore app state after restart.
   */
  fun getSubscribedCentrals(characteristicId: String): List<String>

  companion object {
    /** The codec used by UniversalBlePeripheralChannel. */
    val codec: MessageCodec<Any?> by lazy {
      UniversalBlePeripheralPigeonCodec()
    }
    /** Sets up an instance of `UniversalBlePeripheralChannel` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UniversalBlePeripheralChannel?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.initialize()
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.isAdvertising$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isAdvertising())
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.isSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isSupported())
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.stopAdvertising$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopAdvertising()
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.addService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceArg = args[0] as PeripheralService
            val wrapped: List<Any?> = try {
              api.addService(serviceArg)
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.removeService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeService(serviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.clearServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearServices()
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.getServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getServices())
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.startAdvertising$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val servicesArg = args[0] as List<String>
            val localNameArg = args[1] as String?
            val timeoutArg = args[2] as Long?
            val manufacturerDataArg = args[3] as PeripheralManufacturerData?
            val addManufacturerDataInScanResponseArg = args[4] as Boolean
            val wrapped: List<Any?> = try {
              api.startAdvertising(servicesArg, localNameArg, timeoutArg, manufacturerDataArg, addManufacturerDataInScanResponseArg)
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.updateCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val characteristicIdArg = args[0] as String
            val valueArg = args[1] as ByteArray
            val deviceIdArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.updateCharacteristic(characteristicIdArg, valueArg, deviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.getSubscribedCentrals$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val characteristicIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getSubscribedCentrals(characteristicIdArg))
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class UniversalBlePeripheralCallback(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by UniversalBlePeripheralCallback. */
    val codec: MessageCodec<Any?> by lazy {
      UniversalBlePeripheralPigeonCodec()
    }
  }
  fun onReadRequest(deviceIdArg: String, characteristicIdArg: String, offsetArg: Long, valueArg: ByteArray?, callback: (Result<PeripheralReadRequestResult?>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onReadRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, characteristicIdArg, offsetArg, valueArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          val output = it[0] as PeripheralReadRequestResult?
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onWriteRequest(deviceIdArg: String, characteristicIdArg: String, offsetArg: Long, valueArg: ByteArray?, callback: (Result<PeripheralWriteRequestResult?>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onWriteRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, characteristicIdArg, offsetArg, valueArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          val output = it[0] as PeripheralWriteRequestResult?
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onCharacteristicSubscriptionChange(deviceIdArg: String, characteristicIdArg: String, isSubscribedArg: Boolean, nameArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onCharacteristicSubscriptionChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, characteristicIdArg, isSubscribedArg, nameArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAdvertisingStatusUpdate(advertisingArg: Boolean, errorArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onAdvertisingStatusUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(advertisingArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBleStateChange(stateArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onBleStateChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onServiceAdded(serviceIdArg: String, errorArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onServiceAdded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(serviceIdArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onMtuChange(deviceIdArg: String, mtuArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onMtuChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, mtuArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onConnectionStateChange(deviceIdArg: String, connectedArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onConnectionStateChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, connectedArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBondStateChange(deviceIdArg: String, bondStateArg: PeripheralBondState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onBondStateChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, bondStateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
