// Autogenerated from Pigeon (v26.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.navideck.universal_ble

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object UniversalBlePeripheralPigeonUtils {

  fun createConnectionError(channelName: String): PeripheralFlutterError {
    return PeripheralFlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is PeripheralFlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).contains(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class PeripheralFlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class PeripheralBondState(val raw: Int) {
  BONDING(0),
  BONDED(1),
  NONE(2);

  companion object {
    fun ofRaw(raw: Int): PeripheralBondState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralService (
  val uuid: String,
  val primary: Boolean,
  val characteristics: List<PeripheralCharacteristic>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralService {
      val uuid = pigeonVar_list[0] as String
      val primary = pigeonVar_list[1] as Boolean
      val characteristics = pigeonVar_list[2] as List<PeripheralCharacteristic>
      return PeripheralService(uuid, primary, characteristics)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      primary,
      characteristics,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PeripheralService) {
      return false
    }
    if (this === other) {
      return true
    }
    return UniversalBlePeripheralPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralCharacteristic (
  val uuid: String,
  val properties: List<Long>,
  val permissions: List<Long>,
  val descriptors: List<PeripheralDescriptor>? = null,
  val value: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralCharacteristic {
      val uuid = pigeonVar_list[0] as String
      val properties = pigeonVar_list[1] as List<Long>
      val permissions = pigeonVar_list[2] as List<Long>
      val descriptors = pigeonVar_list[3] as List<PeripheralDescriptor>?
      val value = pigeonVar_list[4] as ByteArray?
      return PeripheralCharacteristic(uuid, properties, permissions, descriptors, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      properties,
      permissions,
      descriptors,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PeripheralCharacteristic) {
      return false
    }
    if (this === other) {
      return true
    }
    return UniversalBlePeripheralPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralDescriptor (
  val uuid: String,
  val value: ByteArray? = null,
  val permissions: List<Long>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralDescriptor {
      val uuid = pigeonVar_list[0] as String
      val value = pigeonVar_list[1] as ByteArray?
      val permissions = pigeonVar_list[2] as List<Long>?
      return PeripheralDescriptor(uuid, value, permissions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uuid,
      value,
      permissions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PeripheralDescriptor) {
      return false
    }
    if (this === other) {
      return true
    }
    return UniversalBlePeripheralPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralReadRequestResult (
  val value: ByteArray,
  val offset: Long? = null,
  val status: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralReadRequestResult {
      val value = pigeonVar_list[0] as ByteArray
      val offset = pigeonVar_list[1] as Long?
      val status = pigeonVar_list[2] as Long?
      return PeripheralReadRequestResult(value, offset, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      value,
      offset,
      status,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PeripheralReadRequestResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return UniversalBlePeripheralPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralWriteRequestResult (
  val value: ByteArray? = null,
  val offset: Long? = null,
  val status: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralWriteRequestResult {
      val value = pigeonVar_list[0] as ByteArray?
      val offset = pigeonVar_list[1] as Long?
      val status = pigeonVar_list[2] as Long?
      return PeripheralWriteRequestResult(value, offset, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      value,
      offset,
      status,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PeripheralWriteRequestResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return UniversalBlePeripheralPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PeripheralManufacturerData (
  val manufacturerId: Long,
  val data: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PeripheralManufacturerData {
      val manufacturerId = pigeonVar_list[0] as Long
      val data = pigeonVar_list[1] as ByteArray
      return PeripheralManufacturerData(manufacturerId, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      manufacturerId,
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PeripheralManufacturerData) {
      return false
    }
    if (this === other) {
      return true
    }
    return UniversalBlePeripheralPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class UniversalBlePeripheralPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PeripheralBondState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralService.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralCharacteristic.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralDescriptor.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralReadRequestResult.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralWriteRequestResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PeripheralManufacturerData.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PeripheralBondState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PeripheralService -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PeripheralCharacteristic -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PeripheralDescriptor -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PeripheralReadRequestResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PeripheralWriteRequestResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PeripheralManufacturerData -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface UniversalBlePeripheralChannel {
  fun initialize()
  fun isAdvertising(): Boolean?
  fun isSupported(): Boolean
  fun stopAdvertising()
  fun addService(service: PeripheralService)
  fun removeService(serviceId: String)
  fun clearServices()
  fun getServices(): List<String>
  fun startAdvertising(services: List<String>, localName: String?, timeout: Long?, manufacturerData: PeripheralManufacturerData?, addManufacturerDataInScanResponse: Boolean)
  fun updateCharacteristic(characteristicId: String, value: ByteArray, deviceId: String?)

  companion object {
    /** The codec used by UniversalBlePeripheralChannel. */
    val codec: MessageCodec<Any?> by lazy {
      UniversalBlePeripheralPigeonCodec()
    }
    /** Sets up an instance of `UniversalBlePeripheralChannel` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: UniversalBlePeripheralChannel?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.initialize()
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.isAdvertising$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isAdvertising())
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.isSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.isSupported())
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.stopAdvertising$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.stopAdvertising()
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.addService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceArg = args[0] as PeripheralService
            val wrapped: List<Any?> = try {
              api.addService(serviceArg)
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.removeService$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val serviceIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.removeService(serviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.clearServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearServices()
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.getServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getServices())
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.startAdvertising$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val servicesArg = args[0] as List<String>
            val localNameArg = args[1] as String?
            val timeoutArg = args[2] as Long?
            val manufacturerDataArg = args[3] as PeripheralManufacturerData?
            val addManufacturerDataInScanResponseArg = args[4] as Boolean
            val wrapped: List<Any?> = try {
              api.startAdvertising(servicesArg, localNameArg, timeoutArg, manufacturerDataArg, addManufacturerDataInScanResponseArg)
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralChannel.updateCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val characteristicIdArg = args[0] as String
            val valueArg = args[1] as ByteArray
            val deviceIdArg = args[2] as String?
            val wrapped: List<Any?> = try {
              api.updateCharacteristic(characteristicIdArg, valueArg, deviceIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              UniversalBlePeripheralPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class UniversalBlePeripheralCallback(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by UniversalBlePeripheralCallback. */
    val codec: MessageCodec<Any?> by lazy {
      UniversalBlePeripheralPigeonCodec()
    }
  }
  fun onReadRequest(deviceIdArg: String, characteristicIdArg: String, offsetArg: Long, valueArg: ByteArray?, callback: (Result<PeripheralReadRequestResult?>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onReadRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, characteristicIdArg, offsetArg, valueArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(PeripheralFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          val output = it[0] as PeripheralReadRequestResult?
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onWriteRequest(deviceIdArg: String, characteristicIdArg: String, offsetArg: Long, valueArg: ByteArray?, callback: (Result<PeripheralWriteRequestResult?>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onWriteRequest$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, characteristicIdArg, offsetArg, valueArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(PeripheralFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          val output = it[0] as PeripheralWriteRequestResult?
          callback(Result.success(output))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onCharacteristicSubscriptionChange(deviceIdArg: String, characteristicIdArg: String, isSubscribedArg: Boolean, nameArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onCharacteristicSubscriptionChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, characteristicIdArg, isSubscribedArg, nameArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(PeripheralFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onAdvertisingStatusUpdate(advertisingArg: Boolean, errorArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onAdvertisingStatusUpdate$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(advertisingArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(PeripheralFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBleStateChange(stateArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onBleStateChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(PeripheralFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onServiceAdded(serviceIdArg: String, errorArg: String?, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onServiceAdded$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(serviceIdArg, errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(PeripheralFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onMtuChange(deviceIdArg: String, mtuArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onMtuChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, mtuArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(PeripheralFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onConnectionStateChange(deviceIdArg: String, connectedArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onConnectionStateChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, connectedArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(PeripheralFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBondStateChange(deviceIdArg: String, bondStateArg: PeripheralBondState, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.universal_ble.UniversalBlePeripheralCallback.onBondStateChange$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceIdArg, bondStateArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(PeripheralFlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(UniversalBlePeripheralPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
